import {
  IconBrandAndroid,
  IconBrandBootstrap,
  IconBrandCss3,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandMysql,
  IconBrandReact,
  IconBrandVue,
  IconBellRinging,
  IconCoffee,
  IconDatabase,
  IconDatabaseEdit,
  IconFileCode,
  IconKey,
  IconLayersLinked,
  IconLayoutDashboard,
  IconLeaf,
  IconNeedleThread,
  IconRefreshDot,
  IconShieldLock,
  IconSql,
  IconStack2,
  IconSitemap,
} from '@tabler/icons-vue'

export const skillIconComponents = {
  vue: IconBrandVue,
  react: IconBrandReact,
  antd: IconLayoutDashboard,
  html5: IconBrandHtml5,
  css3: IconBrandCss3,
  javascript: IconBrandJavascript,
  bootstrap: IconBrandBootstrap,
  java: IconCoffee,
  springboot: IconLeaf,
  springdata: IconDatabaseEdit,
  hibernate: IconStack2,
  mybatis: IconFileCode,
  springsec: IconShieldLock,
  jwt: IconKey,
  postgres: IconDatabase,
  mysql: IconBrandMysql,
  datamodel: IconSitemap,
  sql: IconSql,
  android: IconBrandAndroid,
  mvvm: IconLayersLinked,
  hilt: IconNeedleThread,
  rxjava: IconRefreshDot,
  onesignal: IconBellRinging,
} as const

export type SkillIconKey = keyof typeof skillIconComponents
